# Generated by Django 3.0.7 on 2020-11-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_funcionario', models.CharField(max_length=150)),
                ('matricula', models.IntegerField()),
                ('email_institucional', models.CharField(max_length=100)),
                ('curso_vinculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestoreventos.Curso')),
            ],
        ),
    ]
