# Generated by Django 3.0.7 on 2020-11-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0003_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='curso_vinculado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestoreventos.Curso'),
        ),
    ]
