# Generated by Django 3.0.7 on 2020-11-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0004_auto_20201109_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email_institucional',
            field=models.EmailField(max_length=100),
        ),
    ]
