# Generated by Django 3.1.3 on 2020-11-09 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0005_auto_20201109_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_palestrante', models.CharField(max_length=150)),
                ('dt_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('email_pessoal', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='titulo',
            new_name='nome_do_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='criador_do_evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(default='2011-09-01T13:20:30+03:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(default='2011-09-01T13:20:30+03:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='palestrante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.palestrante'),
            preserve_default=False,
        ),
    ]
