# Generated by Django 3.1.3 on 2020-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0006_auto_20201109_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(default='2020-11-09T13:20:30+03:00'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(default='2020-11-09T13:20:30+03:00'),
        ),
    ]
